Repository career-pirates/resumate-backend, pull requests merged in 2025-09, with the labels that each got.

#24 [FEATURE] 회고 삭제, 영구 삭제, 삭제 복원 기능 구현
  src/main/java/com/careerpirates/resumate/review/application/service/ReviewService.java
  src/main/java/com/careerpirates/resumate/review/docs/ReviewControllerDocs.java
  src/main/java/com/careerpirates/resumate/review/domain/Review.java
  src/main/java/com/careerpirates/resumate/review/infrastructure/ReviewRepository.java
  src/main/java/com/careerpirates/resumate/review/message/success/ReviewSuccess.java
  src/main/java/com/careerpirates/resumate/review/presentation/ReviewController.java
  src/test/java/com/careerpirates/resumate/review/application/service/ReviewServiceTest.java
Labels: ✨ feature

#29 [FEATURE] 회고 삭제 스케줄러 추가
  src/main/java/com/careerpirates/resumate/ResumateBackendApplication.java
  src/main/java/com/careerpirates/resumate/review/infrastructure/ReviewRepository.java
  src/main/java/com/careerpirates/resumate/review/scheduler/ReviewCleanupScheduler.java
Labels: ✨ feature

#31 [FEATURE] 폴더 삭제시 회고를 삭제하도록 변경
  src/main/java/com/careerpirates/resumate/folder/application/service/FolderService.java
  src/main/java/com/careerpirates/resumate/review/infrastructure/ReviewRepository.java
  src/test/java/com/careerpirates/resumate/folder/application/service/FolderServiceTest.java
Labels: ✨ feature

#38 [CHORE] 배포 관련 Dockerfile 생성
  Dockerfile
Labels: ⚙️ chore

#33 [FEATURE] 회고 분석 도메인 구현
  build.gradle
  src/main/java/com/careerpirates/resumate/analysis/domain/Analysis.java
  src/main/java/com/careerpirates/resumate/analysis/domain/AnalysisStatus.java
  src/main/java/com/careerpirates/resumate/analysis/infrastructure/AnalysisRepository.java
Labels: ✨ feature

#42 [CHORE] 배포 DB 변수명 및 값 변경
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#43 [CHORE] develop -> main 병합
  build.gradle
  src/main/java/com/careerpirates/resumate/analysis/domain/Analysis.java
  src/main/java/com/careerpirates/resumate/analysis/domain/AnalysisStatus.java
  src/main/java/com/careerpirates/resumate/analysis/infrastructure/AnalysisRepository.java
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#45 [CHORE] security config formlogin 비활성화
  src/main/java/com/careerpirates/resumate/global/config/SecurityConfig.java
Labels: ⚙️ chore

#48 [CHORE] security Config 로그인 비활성화 및 Swagger ui 허용
  src/main/java/com/careerpirates/resumate/global/config/SecurityConfig.java
Labels: ⚙️ chore

#40 [FEATURE] Spring Security, OAuth2, JWT 기반 코드 구현
  build.gradle
  docker-compose.local.yaml
  src/main/java/com/careerpirates/resumate/ResumateBackendApplication.java
  src/main/java/com/careerpirates/resumate/auth/application/dto/CustomMemberDetails.java
  src/main/java/com/careerpirates/resumate/auth/application/dto/JwtToken.java
  src/main/java/com/careerpirates/resumate/auth/application/dto/request/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/application/dto/response/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/application/dto/response/CurrentUserDto.java
  src/main/java/com/careerpirates/resumate/auth/application/service/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/application/service/AuthService.java
  src/main/java/com/careerpirates/resumate/auth/docs/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/docs/AuthControllerDocs.java
  src/main/java/com/careerpirates/resumate/auth/infrastructure/JwtRepository.java
  src/main/java/com/careerpirates/resumate/auth/message/exception/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/message/exception/JwtErrorCode.java
  src/main/java/com/careerpirates/resumate/auth/message/exception/OAuthErrorCode.java
  src/main/java/com/careerpirates/resumate/auth/message/success/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/message/success/AuthSuccessCode.java
  src/main/java/com/careerpirates/resumate/auth/presentation/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/presentation/AuthController.java
  src/main/java/com/careerpirates/resumate/auth/security/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/careerpirates/resumate/auth/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/careerpirates/resumate/auth/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/careerpirates/resumate/auth/security/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/com/careerpirates/resumate/auth/util/cookie/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/util/cookie/CookieManager.java
  src/main/java/com/careerpirates/resumate/auth/util/jwt/.gitkeep
  src/main/java/com/careerpirates/resumate/auth/util/jwt/JwtExtractor.java
  src/main/java/com/careerpirates/resumate/auth/util/jwt/JwtIssuer.java
  src/main/java/com/careerpirates/resumate/auth/util/jwt/JwtProperties.java
  src/main/java/com/careerpirates/resumate/auth/util/jwt/JwtValidator.java
  src/main/java/com/careerpirates/resumate/global/config/CorsConfig.java
  src/main/java/com/careerpirates/resumate/global/config/CorsProperties.java
  src/main/java/com/careerpirates/resumate/global/config/SecurityConfig.java
  src/main/java/com/careerpirates/resumate/global/config/SwaggerConfig.java
  src/main/java/com/careerpirates/resumate/member/application/service/.gitkeep
  src/main/java/com/careerpirates/resumate/member/application/service/MemberService.java
  src/main/java/com/careerpirates/resumate/member/domain/.gitkeep
  src/main/java/com/careerpirates/resumate/member/domain/entity/Member.java
  src/main/java/com/careerpirates/resumate/member/infrastructure/.gitkeep
  src/main/java/com/careerpirates/resumate/member/infrastructure/MemberRepository.java
  src/main/java/com/careerpirates/resumate/member/message/exception/.gitkeep
  src/main/java/com/careerpirates/resumate/member/message/exception/MemberErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/oauth2.yml
Labels: ✨ feature

#61 [CHORE] application-prod 수정
  build.gradle
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#49 [FEATURE] 회고 분석 요청 및 결과 조회 기능 구현
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/AnalysisResponse.java
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/AnalysisResultDto.java
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/GPTResponse.java
  src/main/java/com/careerpirates/resumate/analysis/application/service/AnalysisService.java
  src/main/java/com/careerpirates/resumate/analysis/application/service/OpenAIService.java
  src/main/java/com/careerpirates/resumate/analysis/config/OpenAIProperties.java
  src/main/java/com/careerpirates/resumate/analysis/docs/AnalysisControllerDocs.java
  src/main/java/com/careerpirates/resumate/analysis/domain/Analysis.java
  src/main/java/com/careerpirates/resumate/analysis/event/AnalysisCompletedEvent.java
  src/main/java/com/careerpirates/resumate/analysis/event/AnalysisErrorEvent.java
  src/main/java/com/careerpirates/resumate/analysis/infrastructure/AnalysisRepository.java
  src/main/java/com/careerpirates/resumate/analysis/message/exception/AnalysisError.java
  src/main/java/com/careerpirates/resumate/analysis/message/success/AnalysisSuccess.java
  src/main/java/com/careerpirates/resumate/analysis/presentation/AnalysisController.java
  src/main/java/com/careerpirates/resumate/global/config/WebClientConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ✨ feature

#72 [CHORE] Swagger 서버 URL 설정
  src/main/java/com/careerpirates/resumate/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#75 [REFACTOR] 회고 분석 결과 재사용 로직 추가
  src/main/java/com/careerpirates/resumate/analysis/application/service/AnalysisService.java
  src/main/java/com/careerpirates/resumate/analysis/docs/AnalysisControllerDocs.java
  src/main/java/com/careerpirates/resumate/analysis/message/exception/AnalysisError.java
  src/main/java/com/careerpirates/resumate/analysis/message/success/AnalysisSuccess.java
  src/main/java/com/careerpirates/resumate/analysis/presentation/AnalysisController.java
  src/main/java/com/careerpirates/resumate/folder/domain/Folder.java
  src/main/java/com/careerpirates/resumate/global/domain/BaseEntity.java
  src/main/java/com/careerpirates/resumate/review/application/service/ReviewService.java
Labels: ♻️ refactor

#88 [FEATURE] 폴더 목록 조회 조건 추가
  src/main/java/com/careerpirates/resumate/folder/application/dto/response/FolderTreeResponse.java
  src/main/java/com/careerpirates/resumate/folder/application/service/FolderService.java
  src/main/java/com/careerpirates/resumate/folder/docs/FolderControllerDocs.java
  src/main/java/com/careerpirates/resumate/folder/infrastructure/FolderRepository.java
  src/main/java/com/careerpirates/resumate/folder/presentation/FolderController.java
  src/test/java/com/careerpirates/resumate/folder/application/service/FolderServiceTest.java
Labels: ✨ feature

#90 [CHORE] Application.yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#93 [FEATURE] 회고 통계 기능 구현
  src/main/java/com/careerpirates/resumate/analysis/application/service/AnalysisService.java
  src/main/java/com/careerpirates/resumate/analysis/infrastructure/AnalysisRepository.java
  src/main/java/com/careerpirates/resumate/member/application/dto/response/.gitkeep
  src/main/java/com/careerpirates/resumate/member/application/dto/response/StatisticsResponse.java
  src/main/java/com/careerpirates/resumate/member/application/service/MemberService.java
  src/main/java/com/careerpirates/resumate/member/application/service/StatisticsService.java
  src/main/java/com/careerpirates/resumate/member/docs/.gitkeep
  src/main/java/com/careerpirates/resumate/member/docs/MemberControllerDocs.java
  src/main/java/com/careerpirates/resumate/member/domain/entity/Member.java
  src/main/java/com/careerpirates/resumate/member/infrastructure/MemberRepository.java
  src/main/java/com/careerpirates/resumate/member/message/success/.gitkeep
  src/main/java/com/careerpirates/resumate/member/message/success/MemberSuccessCode.java
  src/main/java/com/careerpirates/resumate/member/presentation/.gitkeep
  src/main/java/com/careerpirates/resumate/member/presentation/MemberController.java
  src/main/java/com/careerpirates/resumate/review/application/service/ReviewService.java
  src/main/java/com/careerpirates/resumate/review/infrastructure/ReviewRepository.java
Labels: ✨ feature

#95 [FEATURE] 닉네임 설정 기능 구현 #94
  src/main/java/com/careerpirates/resumate/auth/application/dto/response/CurrentUserDto.java
  src/main/java/com/careerpirates/resumate/member/application/dto/request/.gitkeep
  src/main/java/com/careerpirates/resumate/member/application/dto/request/SetNicknameRequest.java
  src/main/java/com/careerpirates/resumate/member/application/service/MemberService.java
  src/main/java/com/careerpirates/resumate/member/message/success/MemberSuccessCode.java
  src/main/java/com/careerpirates/resumate/member/presentation/MemberController.java
Labels: ✨ feature

#96 [REFACTOR] OpenAI API 호출 Bucket4j 적용
  build.gradle
  src/main/java/com/careerpirates/resumate/analysis/application/service/OpenAIService.java
  src/main/java/com/careerpirates/resumate/analysis/config/OpenAIRateLimiter.java
  src/main/java/com/careerpirates/resumate/analysis/message/exception/AnalysisError.java
  src/test/java/com/careerpirates/resumate/analysis/application/service/OpenAIServiceTest.java
Labels: ♻️ refactor

#102 [FEATURE] 분석 결과 조회 기능 수정
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/AnalysisListResponse.java
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/AnalysisResponse.java
  src/main/java/com/careerpirates/resumate/analysis/application/dto/response/AnalysisSimpleResponse.java
  src/main/java/com/careerpirates/resumate/analysis/application/service/AnalysisService.java
Labels: ✨ feature
